# Generated by Django 5.0.3 on 2024-03-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='appt_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='number_of_employees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='in_stock',
            field=models.IntegerField(),
        ),
    ]
